# Generated by Django 5.0.1 on 2024-01-08 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproject', models.CharField(max_length=50)),
                ('deliverytime', models.DateTimeField()),
                ('fileEN', models.FileField(upload_to='')),
                ('fileAR', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outputAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceEN', models.TextField(max_length=1000)),
                ('sentenceAR', models.TextField(max_length=1000)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.CharField(choices=[('correct translation', 'correct translation'), ('not verified yet', 'not verified yet'), ('re-translated', 're-translated')], default='not verified yet', max_length=25)),
                ('nameproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='translationSite.project')),
            ],
        ),
    ]
