# Generated by Django 3.2.25 on 2024-08-12 08:45

from django.db import migrations, models
import translationSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0001_initial'),
    ]

 