# Generated by Django 3.2.25 on 2024-06-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processed_output_ai',
            name='rfk',
        ),
        migrations.RemoveField(
            model_name='project1',
            name='author',
        ),
        migrations.DeleteModel(
            name='output_AI',
        ),
        migrations.DeleteModel(
            name='processed_output_AI',
        ),
        migrations.DeleteModel(
            name='project1',
        ),
    ]
