# Generated by Django 3.2.25 on 2024-06-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translationSite', '0002_auto_20240619_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='output_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileAR', models.FileField(upload_to='out_ai')),
            ],
        ),
        migrations.CreateModel(
            name='project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliverytime', models.DateField()),
                ('fileAR', models.FileField(null=True, upload_to='input')),
                ('fileEN', models.FileField(upload_to='input')),
                ('updated_dt', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='processed_output_AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceEN', models.TextField(max_length=1000)),
                ('sentenceAR', models.TextField(max_length=1000)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.CharField(choices=[('ct', 'correct translation'), ('ny', 'not verified yet'), ('rt', 're-translated')], default='ny', max_length=2)),
                ('rfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='translationSite.output_ai')),
            ],
            options={
                'ordering': ['starttime'],
            },
        ),
        migrations.AddField(
            model_name='output_ai',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='translationSite.project1'),
        ),
        migrations.AddIndex(
            model_name='project1',
            index=models.Index(fields=['-publish'], name='translation_publish_053c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='processed_output_ai',
            index=models.Index(fields=['starttime'], name='translation_startti_03133f_idx'),
        ),
    ]
