# Generated by Django 5.0.1 on 2024-01-10 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0002_rename_nameproject_outputai_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project46',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliverytime', models.DateTimeField()),
                ('fileEN', models.FileField(upload_to='')),
                ('fileAR', models.FileField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AlterField(
            model_name='outputai',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='translationSite.project46'),
        ),
        migrations.AddIndex(
            model_name='project46',
            index=models.Index(fields=['-publish'], name='translation_publish_e2038e_idx'),
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
