# Generated by Django 5.0.1 on 2024-01-10 17:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0003_project46_alter_outputai_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project46',
            new_name='project',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='translation_publish_2f3362_idx',
            old_name='translation_publish_e2038e_idx',
        ),
    ]
