# Generated by Django 3.2.25 on 2024-06-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='output_AI',
            new_name='output_AI1',
        ),
    ]
