# Generated by Django 5.0.1 on 2024-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0004_rename_project46_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputai',
            options={'ordering': ['starttime']},
        ),
        migrations.AddIndex(
            model_name='outputai',
            index=models.Index(fields=['starttime'], name='translation_startti_e90d23_idx'),
        ),
    ]
