# Generated by Django 3.2.25 on 2024-06-21 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translationSite', '0005_auto_20240621_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliverytime', models.DateField()),
                ('fileAR', models.FileField(null=True, upload_to='input')),
                ('fileEN', models.FileField(upload_to='input')),
                ('updated_dt', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='project1',
            index=models.Index(fields=['-publish'], name='translation_publish_053c8b_idx'),
        ),
    ]
