# Generated by Django 3.2.25 on 2024-07-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project1',
            options={'permissions': [('can_view_project', 'Can view project'), ('can_edit_project', 'Can edit project')]},
        ),
        migrations.RemoveIndex(
            model_name='project1',
            name='translation_publish_053c8b_idx',
        ),
    ]
