# Generated by Django 3.2.25 on 2024-07-25 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translationSite', '0007_auto_20240707_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project1',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-publish']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-publish'], name='translation_publish_2f3362_idx'),
        ),
    ]
