# Generated by Django 3.2.25 on 2024-07-25 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translationSite', '0009_projectmember1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMember1',
            new_name='ProjectMember',
        ),
    ]
