# Generated by Django 3.2.25 on 2024-07-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translationSite', '0010_rename_projectmember1_projectmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='permission_type',
        ),
    ]
